### ISSUE TITLE
Detecting Changes in table in order to detect when any changes

### ISSUE THREAD

**Issue by Vijaykumarj** [jasonsturges/mysql-dotnet-core#8] opened 2018-06-22 09:25 UTC
Receive Notifications when a table record changes between an asp.net web application and an instance of mysql like **SQLDependency in SQL Server.**

thanks in advance

**Comment by bgrainger** [comment] 2018-06-22 14:16
Duplicate of mysql-net/MySqlConnector#522.

**Comment by jasonsturges** [comment] 2020-06-11 02:47
This now works with DotNetCore 3.1, and MySQL 8.

Hopefully all issues are now resolved.

**Closed by jasonsturges** 2020-06-11 02:47 UTC
